woowacourse-teams/2024-ddangkong

backend/.github/workflows/be-cd-dev.yml
backend/.github/workflows/be-ci-dev.yml
backend/build.gradle

#18 
- AWS ssh 포트, IAM 사용 권한이 제한된 상황에서 가능한 CI/CD 스크립트를 작성하여
자동 배포를 수행하도록 만든다.
- BE Dev 환경 CI 세팅
- BE Dev 환경 CD 세팅
- BE Dev 운영환경(EC2)에 Github self hosted Runner 세팅
- 22번 포트가 우테코 LAN 에서만 사용할 수 있기 때문에 self hosted runner로 EC2 내부에서 CD 스크립트를 동작하도록 한다.

[FEAT] BE Dev 환경 CI/CD 스크립트 작성

---

backend/.github/workflows/be-cd-dev.yml

#22 
cd 스크립트 동작 시점이 `Develop 브랜치에 PR이 생성되었을 때` 로 설정되어 있었다.
cd 스크립트 동작 시점을 `Develop 브랜치에 Push가 발생했을 때` 로 변경하였다.

[FIX] cd 스크립트 동작 시점 PR -> Push 시점으로 변경

---

backend/src/main/java/ddangkong/controller/exception/ErrorResponse.java
backend/src/main/java/ddangkong/controller/exception/GlobalExceptionHandler.java
backend/src/main/java/ddangkong/domain/member/Member.java
backend/src/main/java/ddangkong/domain/option/BalanceOption.java
backend/src/main/java/ddangkong/domain/question/BalanceQuestion.java
backend/src/main/java/ddangkong/domain/question/Category.java
backend/src/main/java/ddangkong/domain/room/Room.java
backend/src/main/java/ddangkong/domain/room/RoomQuestion.java
backend/src/main/java/ddangkong/domain/vote/BalanceVote.java
backend/src/test/resources/application.yml

#19 
ERD에 맞추어 사용할 Entity 필요
ERD에 맞추어 Entity 생성
- 깃 메시지 컨벤션
- 다음에는 모든 커밋에 이슈 번호를 달도록 하겠습니다. 죄송합니다 ( _ _ )
- 리뷰 포인트
- 패키지 구조
- domain.member.Member 형식으로 패키지 구성
- domain.question.BalanceQuestion으로 구성함
- 빈칸 채우기 문제 등이 추가 될 때를 고려해서 domain.balance.question.BalanceQuestion과 같이 해야될까? 아니면 그 때 가서 패키지 구조를 바꾸는 것으로 할까?
- `@Entity`, `@ManyToOne`에 추가적으로 들어가야 할 옵션이 필요한가?
- ERD에 맞게 설계되어 있는가? 오타가 있지는 않은가?
- [ERD 링크](https://www.erdcloud.com/d/8WoFz6FREzz952yTM) 
- 테스트 환경 재구성 필요 (이번 PR or 다음 PR)
- 테스트는 통과하나, 모든 테이블에 대해 다음과 같은 에러 메시지가 출력됨
```
2024-07-17T17:20:10.272+09:00  WARN 22008 --- [    Test worker] o.h.t.s.i.ExceptionHandlerLoggedImpl     : GenerationTarget encountered exception accepting command : Error executing DDL "
alter table balance_option 
drop 
foreign key FK2ras98xgctlpk1f4trqxp6hiu" via JDBC …
```

[FEAT] ERD에 따른 Entity 구현

---

frontend/package-lock.json
frontend/package.json
frontend/src/index.tsx
frontend/src/mocks/wrapper.tsx

#47 
같은 라이브러리 설치 시 package-lock.json 꼬일 위험 존재
의존성 꼬일 것을 우려하여 recoil 라이브러리를 미리 설치하여 package-lock.json 공유
코드 반영은 되지 않았지만 로컬에서 실행해본 결과 화면
```tsx
export const topicAtomState = atom({
key: '',
default: 'hello',
});
const TopicContainer = () => {
const { balanceContent } = useBalanceContentQuery();
const topic = useRecoilValue(topicAtomState);
...
}
```

[FEAT] recoil 라이브러리 설치

---

backend/src/test/java/ddangkong/controller/BaseControllerTest.java
backend/src/test/java/ddangkong/domain/BaseRepositoryTest.java
backend/src/test/java/ddangkong/domain/balance/content/RoomContentRepositoryTest.java
backend/src/test/java/ddangkong/service/BaseServiceTest.java
backend/src/test/java/ddangkong/support/extension/DatabaseCleanerExtension.java
backend/src/test/resources/init-test.sql

close #37 
- 테스트간 격리 필요
- 데이터를 삽입하는 sql 스크립트에 DDL과 DML 혼재
- DB의 모든 table들을 truncate하는 extension 적용
- controller
- service
> `@DataJpaTest`는 제외
- sql 스크립트에서 DDL 제거 및 formatting
코드와 함께 설명을 첨부합니다
```java
public class DatabaseCleanerExtension implements BeforeEachCallback { // (1)
@Override
public void beforeEach(ExtensionContext extensionContext) {
ApplicationContext context = SpringExtension.getApplicationContext(extensionContext); // (2)
cleanup(context);
}
private void cleanup(ApplicationContext context) {
EntityManager em = context.getBean(EntityManager.class); // (3)
TransactionTemplate transactionTemplate = context.getBean(TransactionTemplate.class);
transactionTemplate.execute(action -> { // (4)
em.clear();
truncateTables(em);
return null;
});
}
private void …
```

[FEAT] truncate extension

---

backend/src/main/java/ddangkong/controller/balance/content/dto/BalanceContentResponse.java
backend/src/main/java/ddangkong/controller/exception/GlobalExceptionHandler.java
backend/src/main/java/ddangkong/domain/balance/content/Room.java
backend/src/main/java/ddangkong/domain/balance/content/RoomContent.java
backend/src/main/java/ddangkong/domain/balance/content/RoomContentRepository.java
backend/src/main/java/ddangkong/domain/balance/content/RoomRepository.java
backend/src/main/java/ddangkong/exception/BadRequestException.java
backend/src/main/java/ddangkong/exception/InternalServerErrorException.java
backend/src/main/java/ddangkong/exception/InternalServerException.java
backend/src/main/java/ddangkong/service/balance/content/BalanceContentService.java
backend/src/main/java/ddangkong/service/excpetion/BusinessLogicException.java
backend/src/main/java/ddangkong/service/excpetion/ViolateDataException.java
backend/src/test/java/ddangkong/controller/balance/content/BalanceContentControllerTest.java
backend/src/test/java/ddangkong/domain/balance/content/RoomContentRepositoryTest.java
backend/src/test/java/ddangkong/service/balance/content/BalanceContentServiceTest.java
backend/src/test/resources/init-test.sql

#52 
- Sprint 2 P2에 맞추어 주제, 선택지 조회 API 변경
- 회의에서 논의된 Exception 관리 적용
- 변경된 ERD 적용 (v1.1)
- 변경된 주제, 선택지 조회 API 적용
- 공통적으로 사용할 로직을 빠르게 반영하는 것을 목표로 했습니다!

[FEAT] 수정된 주제, 선택지 조회 API 반영

---

backend/src/main/java/ddangkong/controller/balance/member/dto/MemberResponse.java
backend/src/main/java/ddangkong/controller/balance/room/RoomController.java
backend/src/main/java/ddangkong/controller/balance/room/dto/RoomJoinRequest.java
backend/src/main/java/ddangkong/controller/balance/room/dto/RoomJoinResponse.java
backend/src/main/java/ddangkong/domain/balance/content/Room.java
backend/src/main/java/ddangkong/domain/balance/content/RoomRepository.java
backend/src/main/java/ddangkong/domain/member/Member.java
backend/src/main/java/ddangkong/domain/member/MemberRepository.java
backend/src/main/java/ddangkong/service/balance/room/RoomService.java
backend/src/test/java/ddangkong/controller/balance/room/RoomControllerTest.java
backend/src/test/java/ddangkong/service/balance/room/RoomServiceTest.java
backend/src/test/resources/init-test.sql

#56 
Sprint 2 P2에 맞추어 주제, 방 생성 및 참여 API 구현
- 방 생성 API 추가
- 방 참여 API 추가
- [X] 테스트가 전부 통과되었나요?

[FEAT] 방 생성 및 참여 기능 구현

---

backend/src/main/java/ddangkong/controller/balance/content/dto/BalanceContentResponse.java
backend/src/main/java/ddangkong/controller/balance/room/RoomController.java
backend/src/main/java/ddangkong/controller/balance/room/dto/RoomMemberResponse.java
backend/src/main/java/ddangkong/controller/balance/room/dto/RoomMembersResponse.java
backend/src/main/java/ddangkong/domain/balance/room/Room.java
backend/src/main/java/ddangkong/domain/balance/room/RoomContent.java
backend/src/main/java/ddangkong/domain/balance/room/RoomContentRepository.java
backend/src/main/java/ddangkong/domain/balance/room/RoomRepository.java
backend/src/main/java/ddangkong/domain/member/Member.java
backend/src/main/java/ddangkong/domain/member/MemberRepository.java
backend/src/main/java/ddangkong/service/balance/content/BalanceContentService.java
backend/src/main/java/ddangkong/service/balance/room/RoomService.java
backend/src/test/java/ddangkong/controller/balance/room/RoomControllerTest.java
backend/src/test/java/ddangkong/domain/balance/content/RoomContentRepositoryTest.java
backend/src/test/java/ddangkong/domain/balance/room/RoomContentRepositoryTest.java
backend/src/test/java/ddangkong/service/balance/room/RoomServiceTest.java
backend/src/test/resources/application.yml
backend/src/test/resources/init-test.sql

#62 
실시간으로 방의 대기 멤버 상태를 확인하기 위한 API가 필요하다.
밸런스 게임 대기방의 전체 멤버를 조회하는 API를 구현하였다.

[FEAT] 방 전체 멤버 조회

---

backend/src/main/java/ddangkong/controller/balance/content/dto/BalanceContentGroupResponse.java
backend/src/main/java/ddangkong/controller/balance/content/dto/BalanceContentTotalResponse.java
backend/src/main/java/ddangkong/controller/balance/option/dto/BalanceOptionGroupResponse.java
backend/src/main/java/ddangkong/controller/balance/option/dto/BalanceOptionTotalResponse.java
backend/src/main/java/ddangkong/controller/balance/vote/BalanceVoteController.java
backend/src/main/java/ddangkong/controller/balance/vote/dto/BalanceVoteResultResponse.java
backend/src/main/java/ddangkong/domain/balance/content/BalanceContentRepository.java
backend/src/main/java/ddangkong/domain/balance/option/BalanceOptionRepository.java
backend/src/main/java/ddangkong/domain/balance/vote/BalanceVote.java
backend/src/main/java/ddangkong/domain/balance/vote/BalanceVoteRepository.java
backend/src/main/java/ddangkong/domain/member/MemberRepository.java
backend/src/main/java/ddangkong/service/balance/content/BalanceContentService.java
backend/src/main/java/ddangkong/service/balance/room/RoomService.java
backend/src/main/java/ddangkong/service/balance/vote/BalanceVoteService.java
backend/src/test/java/ddangkong/service/balance/content/BalanceContentServiceTest.java
backend/src/test/java/ddangkong/service/balance/room/RoomServiceTest.java
backend/src/test/java/ddangkong/service/balance/vote/BalanceVoteServiceTest.java
backend/src/test/resources/init-test.sql

#68  
참가자의 투표 결과 및 전체 사용자의 투표 통계를 조회하는 기능을 제공한다.
- 투표 결과 조회 API 추가
- 투표 결과를 전달해주기 위한 DTO들 추기
- 관련 테스트 및 테스트 데이터 추가
자꾸 커밋할 때 이슈 번호 까먹는데 주의하겠습니다! 🙇‍♂️

[FEAT]: 선택지별 투표 결과 조회 API 구현

---

backend/src/docs/asciidoc/balanceVote.adoc
backend/src/docs/asciidoc/index.adoc
backend/src/test/java/ddangkong/documentation/balance/vote/BalanceVoteDocumentationTest.java

Closed #89
투표에 대한 API 문서가 노션으로만 존재
- Spring rest docs 를 활용한 Room API Test 추가
- room.adoc 추가
- index.adoc 에 room.adoc 경로 추가
#86 의 리뷰를 일부 참고해서 반영했습니다~

[TEST] BalanceVote API 문서 테스트 추가

---

.github/workflows/be-cd-dev.yml
.github/workflows/be-ci-dev.yml

#100
CD docker image pull 과정에서 발생하는 멈춤 현상 발생
- 문제 해결을 위해 확인해본 결과, 기존 버전의 이미지를 모두 삭제하니 정상적으로 작동하는 것을 확인하여
기존 이미지 삭제 스크립트 추가하는 방향으로 해결
- 또한 스크립트가 긴 시간동안 종료되지 않아도 계속해서 돌아가기 때문에 타임아웃을 통해 적절히 끊어줄 필요성을 느낌
[커밋 내용](https://github.com/woowacourse-teams/2024-ddangkong/pull/104/commits/40dbafcde81acf02e12c59b71bad70d45360364d)
[커밋 내용](https://github.com/woowacourse-teams/2024-ddangkong/pull/104/commits/13e0a328bbc350a09a79fc7c3d91486285ec101c)
- CI - 4분
- 약 100개의 CI 스크립트 동작 시간 중 1분 50초가 최대 시간이었음. 때문에 현재 소요되는 시간의 2배인 4분을 넘는 순간 문제가 생긴 것으로 간주
- CD - 4분 
- 125개의 CD 스크립트의
- build job 동작 시간 중 1분 33초가 최대 시간이었음. 때문에 현재 소요되는 시간의 약 2배인 3분을 넘는 순간 문제가 생긴 것으로 간주
- deploy job 동작 시간 중 21초가 최대 시간이었음. 때문에 현재 소요되는 시간의 약 2배인 1분을 넘는 순간 문제가 생긴 것으로 간주

[FIX] CD `docker image pull` 과정에서 멈춤 현상 해결

---

backend/src/docs/asciidoc/room.adoc
backend/src/main/java/ddangkong/controller/balance/room/RoomController.java
backend/src/main/java/ddangkong/controller/balance/room/dto/RoomInfoResponse.java
backend/src/main/java/ddangkong/controller/balance/room/dto/RoomSettingRequest.java
backend/src/main/java/ddangkong/controller/balance/room/dto/RoomSettingResponse.java
backend/src/main/java/ddangkong/domain/balance/room/Room.java
backend/src/main/java/ddangkong/service/balance/room/RoomService.java
backend/src/main/resources/sql/data-dev.sql
backend/src/test/java/ddangkong/controller/balance/room/RoomControllerTest.java
backend/src/test/java/ddangkong/documentation/BaseDocumentationTest.java
backend/src/test/java/ddangkong/documentation/balance/room/RoomDocumentationTest.java
backend/src/test/java/ddangkong/domain/balance/room/RoomTest.java
backend/src/test/java/ddangkong/service/balance/room/RoomServiceTest.java
backend/src/test/resources/init-test.sql

#107
- (P2)방 설정에 필요한 API를 구현해야한다.
- Room Entity에 category필드 추가(ERD 반영완료)
- 해당 값이 추가됨에 따라 방 정보 조회 API (#94)의 ResponseDto에도 category값이 추가되었다.
- 방 설정 정보 변경 API 구현
- default RestDocs Host가 `ddangkong.io`로 되어있는 것을 확인하고, 이번에 확정된 `ddangkong.kr`로 수정하였습니다.
- 방 정보 조회 API 구현 때 놓쳤던 Controller 메서드 ResponseStatus 애노테이션을 추가하였습니다.
- 커밋ID를 착각했습니다.. 수정해야할 것 같은데 도움주실 분 구합니다.

[FEAT] 방 설정 정보 변경 API 구현

---

.github/workflows/be-cd-dev.yml

#116 
정상적인 상황에서 CD deploy job 타임아웃으로 인한 배포 실패가 발생하였다.
CD deploy job에 1분의 추가 여유시간을 두는 것으로 설정한다.

[REFACTOR] cd deploy job 시간제한 2분으로 조정

---

.github/workflows/be-ci-dev.yml

#120 
- 현재 CI를 ubuntu-lasted로 하면 루프에 걸리는 문제가 발생.
- 다른 팀들도 동일한 문제가 있는 것을 보아 Organization 문제인듯.
- 추후 문제 해결시 다시 ubuntu-lasted로 돌아갈 예정
- runs-on 을 ubuntu-lasted -> self-hosted-runner 로 변경
- [x] 테스트가 전부 통과되었나요?
CI 파일 수정은 트리거로 잡히지 않아서 수동으로 돌려보았는데 정상동작합니다!

[FIX] Backend CI runner 를 self-hosted로 변경

---

.github/workflows/be-cd-dev.yml
backend/src/main/resources/sql/data-dev.sql

close #131 
새롭게 추가된 RoomContent의 isUsed 필드가 운영 환경에 있는 data-dev.sql 파일에는 없어서 버그 발생
- data-dev.sql  에서 room_content 테이블에 is_used 필드 추가 
- CD 에서 컨테이너 삭제 확인 출력문 추가

[FIX] 운영 환경 쿼리문 수정 

---

.github/workflows/be-cd-dev.yml
.github/workflows/be-ci-dev.yml
backend/build.gradle

close #118 
api 문서 노출을 개발 환경으로 제한한다.
- REST Docs test 분리 (documentation 테스트만 실행)
- gradle 명령어에 `-PcreateRestDocs` 옵션을 사용해야 REST Docs 관련 task가 동작하도록 변경
- dev CI에서 test task 실행하도록 변경
- dev CD에서 bootJar task에  REST Docs 관련 task 포함
옵션을 사용하지 않아 restDocsTest, asciidoctor task을 포함하지 않고 bootJar, test 후 빌드
<br/>
bootJar는 test task에 의존하지 않으므로 test 실행 x
옵션을 사용하여 restDocsTest, asciidoctor task을 포함해서 bootJar 실행
최적화를 위해서 test task에 documentation 테스트를 제외하도록 구성해볼까 했지만 로컬에서 확인할 때 불편할 것 같아서 반영하지 않았습니다
\+ CI 단계에서 documentation 테스트도 통과하는지 확인하기 위함
```gradle
// build.gradle
tasks.named('test') {
useJUnitPlatform()
filter {
excludeTestsMatching 'ddangkong.documentation.*'
}
}
```
documentation 패키지 하위의 모든 테스트를 제외합니다
인텔리제이 상에서 모든 테스트를 돌려도 documentation을 제외해서 돌리기 때문에 adoc 스니펫이 생성되지 않습니다
로컬에서 adoc 스니펫을 생성해서 rest …

[REFACTOR] 운영 환경 Rest Docs 생성 제외

---

.github/workflows/fe-cd-storybook.yml
.github/workflows/fe-ci-dev.yml
frontend/.gitignore

#125 
- storybook을 배포하지 않아 매번 캡처해서 보내주거나 리뷰어가 로컬에서 돌려봐야함
- github actions를 활용해 storybook 배포를 자동화하여 팀원이 만든 컴포넌트 확인
- github pages 활용하여 storybook 배포
- organization 권한 없을으로 chromatic 불가
- codebuild로 서비스랑 함께 배포하려고 했으나 디렉토리 분리가 안되서 실패 (이건 내가 못하는 걸수도) -> 성공
- [github script](https://github.com/actions/github-script?tab=readme-ov-file) 참고해서 스크립트 수정 [(octokit.js)](https://octokit.github.io/rest.js/v20)

[REFACTOR] storybook 배포 자동화

---

.github/workflows/be-cd-dev.yml
backend/src/main/java/ddangkong/config/CorsConfig.java

#145 
- 현재 프론트엔드에서 **`CloudFront`** 로 배포했기 때문에 HTTPS로 동작하고 있었다.
하지만 백엔드의 API 서버는 HTTP 프로토콜로 동작하고 제공하고 있었기 때문에
HTTPS인 프론트는 API 서버를 사용할 수 없었다.
때문에 HTTP로 제공되던 API를 HTTPS 로 변경하는 작업을 하고자 하였다.
- IP 주소를 외워서 사용하는 것보다, 이해하기 쉬운 영문 주소를 활용하는 것이 훨씬 편리하다.
- EC2의 탄력적IP를 사용할 것이 아니기 때문에 IP 주소가 변경될 가능성이 있는데,
그에 따라 클라이언트에서 요청을 보내는 API주소를 변경하여 재배포하지 않으면 API 요청이 이루어지지 않는다. 이때 클라이언트를 재배포하는 것보다 가비아에서 A레코드에 작성된 API서버 주소만 변경해주는 것이 더 좋은 방안이라고 생각했다.
https://www.notion.so/ghenmaru/HTTPS-DNS-with-certbot-d76459524ee646e28ebf0e0772957710

[FEAT] HTTPS, DNS 설정

---

backend/src/docs/asciidoc/balanceVote.adoc
backend/src/docs/asciidoc/exception.adoc
backend/src/docs/asciidoc/room.adoc
backend/src/test/java/ddangkong/documentation/BaseDocumentationTest.java

#161 
- REST Docs 방 설정 변경 Request 문서에 request-fields 내용이 빠져있었다.
- Domain 주소가 api.dev.ddangkong.kr로 변경되면서 기존 문서에 작성되어 있던 도메인 주소를 수정하게 되었다.
- 방 설정 변경 Request 문서에 request-fields 내용 추가
- 문서 상의 Domain 주소를 api.dev.ddangkong.kr로 변경하였다.
- API 별로 구분 라인을 추가해서 가독성을 높였다.

[FIX] API 문서 오류 수정

---

.github/workflows/be-document-notification-dev.yml

#163 
최근 프론트에서 API 문서가 변경된 것을 인지하지 못하고 이전 버전의 API를 호출하느라 오랜 시간을 허비하는 일이 발생했다.
이 일을 통해 REST Docs 변경 시, 백엔드가 클라이언트에게 제대로 전달해주지 않는다면
클라이언트 측에서 즉각적으로 변경을 인지하기 힘들어 위와 같은 문제가 반복될 것이라는 생각이 들었다.
때문에 API 문서 변경 알림 과정을 자동화하여 문제를 해보고자 한다.
현재 사용하는 협업 툴인 Discord를 통해 REST Docs 문서 관련 코드 변경 시, 알림을 전달한다.
[Ddangkong Notion](https://www.notion.so/ghenmaru/v1-0-0b1d537d8ea641a697ed24ad742a07f7?pvs=4)

[FEAT] 문서 변경 알림 Notificator 스크립트 설정

---

.github/workflows/fe-cd-storybook.yml
frontend/.storybook/preview.tsx
frontend/index.html
frontend/src/styles/GlobalStyle.ts

#149 
- 브라우저마다 폰트가 다르게 적용되고, 폰트마다 기본 크기가 달라 UI가 깨지는 문제 발생
구글 웹폰트 Pretandard 적용
크롬은 적용된 게 크게 차이안나서, 사파리 브라우저로 확인
- 추후 다른 폰트로 바꿀 수도 있음
- preload 적용하면 빠른 것 까진 확인했는데 폰트가 제대로 적용되지 않아 일단 패스

[REFACTOR] Pretandard 폰트 설정

---

backend/src/main/java/ddangkong/service/room/balance/roomvote/RoomBalanceVoteService.java
backend/src/main/java/ddangkong/service/room/balance/roomvote/dto/VoteFinishedResponse.java
backend/src/main/java/ddangkong/util/PercentageCalculator.java
backend/src/test/java/ddangkong/util/PercentageCalculatorTest.java

close #189
- 라운드 종료 검증 로직이 시간이 끝났는지만을 확인함(전원 투표는 확인하지 않았음)
- PercentageCalculator 에서 totalCount가 0인 경우 에러가 발생한다.
- total_balance_vote 가 비어있어서 예외가 발생했었음
- 라운드 종료 확인 메서드에 전원 투표 검증 추가
- PercentageCalculator의 totalCount 가 0인 경우 50을 리턴하도록 변경

[FIX] 라운드 결과 조회 시, 전원이 투표 했음에도 결과가 조회되지 않는 버그 수정

---

backend/src/main/java/ddangkong/controller/room/RoomController.java
backend/src/main/java/ddangkong/domain/room/Room.java
backend/src/main/java/ddangkong/domain/room/RoomRepository.java
backend/src/main/java/ddangkong/service/room/RoomService.java
backend/src/main/java/ddangkong/service/room/dto/RoomJoinResponse.java
backend/src/main/resources/sql/data-dev.sql
backend/src/test/java/ddangkong/controller/room/RoomControllerTest.java
backend/src/test/java/ddangkong/documentation/room/RoomDocumentationTest.java
backend/src/test/java/ddangkong/domain/room/RoomTest.java
backend/src/test/java/ddangkong/domain/room/balance/roomcontent/RoomContentTest.java
backend/src/test/java/ddangkong/service/room/RoomServiceTest.java
backend/src/test/resources/init-test.sql

close #191 
게임 방에 접속할 때, 방의 PK를 통해 접속하기 때문에 외부에서 아무런 방이나 숫자만 바꾸면 마음껏 접속이 가능하다.
이러한 문제를 막기 위해 방 아이디를 사용하던 기존 방식을 UUID를 사용하도록 변경한다.
현재는 Join만 UUID로 다루는 이유
지금은 roomId만 알면 room과 관련된 특정 동작들을 수행시킬 수 있지만
memberId를 쿠키를 통해 받는 로직을 이번 4차 스프린트 과정에서 추가하면서,
요청을 보낸 member가 특정 방에 속해있는 member가 맞아야 요청을 수행할 수 있도록 처리한다면(다음 PR이 될 것 같네요)
사실상 방의 UUID를 통해 입장한 회원이 아니면 roomId를 알아도 무언가 할 수 없으니
일단 요정도로 괜찮을 것 같다고 생각했다.
- 방 join, 방 create API에서 roomId 뿐만 아니라 uuid도 함께 Response하게 되면서 
하나의 ResponseDTO객체에 담아야할 지 고민이 됐습니다만 프론트엔드 수정을 최소화하기 위해 고민만 하고 건드리진 않았습니다. 의견 부탁드려요~!
- 방 참여 API의 RestDocs에 roomId에 대한 설명이 "생성한 방의 ID"로 되어 있어서 "참여한 방"으로 변경하였습니다.

[FEAT] 방 접속 시 API Path에 사용하는 RoomID를 UUID로 변경

---

.github/workflows/be-cd-prod.yml
backend/src/main/resources/application-prod.yml
backend/src/main/resources/logback-dev.xml
backend/src/main/resources/logback-prod.xml

Closed #194 
- 운영 환경에서의 로그 필요
- 운영 환경에서 로그 저장 실시
- 파일 저장 로그
- DEBUG 수준의 ddangkong 패키지 내 발생한 로그
- 로그 파일은 365일까지 보관
- 날짜 별로 다른 파일을 사용함
- 디스코드 알림
- ERROR 수준의 로그가 발생하면 Discord로 알림을 준다.
- https://www.notion.so/ghenmaru/Prod-ef6a2de56c5b43539300f74cd8b4f643

[FEAT] Prod 환경 로그 설정

---

backend/src/main/java/ddangkong/domain/room/balance/roomvote/RoomBalanceVoteRepository.java
backend/src/main/java/ddangkong/domain/room/member/Member.java
backend/src/main/java/ddangkong/facade/balance/vote/dto/GiveUpVoteMemberResponse.java
backend/src/main/java/ddangkong/facade/room/balance/roomvote/RoomBalanceVoteFacade.java
backend/src/main/java/ddangkong/facade/room/balance/roomvote/dto/ContentRoomBalanceVoteResponse.java
backend/src/main/java/ddangkong/service/room/balance/roomvote/RoomBalanceVoteService.java
backend/src/main/java/ddangkong/util/PercentageCalculator.java
backend/src/test/java/ddangkong/controller/room/RoomControllerTest.java
backend/src/test/java/ddangkong/documentation/room/balance/roomvote/RoomBalanceVoteDocumentationTest.java
backend/src/test/java/ddangkong/facade/room/RoomFacadeTest.java
backend/src/test/java/ddangkong/facade/room/balance/roomvote/RoomBalanceVoteFacadeTest.java
backend/src/test/java/ddangkong/util/PercentageCalculatorTest.java
backend/src/test/resources/init-test.sql

close #208
선택지 별 투표 결과 조회 시 기권자 정보가 표시되지 않아 누가 기권했는 지 확인할 수 없다.
선택지별 투표 결과 API Response DTO에 기권자 정보 추가
- https://www.notion.so/ghenmaru/API-09fecba367f449b1b37c0a80d8f1dded?pvs=4
- RestDocs 문서가 `./gradlew bootJar -DcreateRestDocs` 로 아티팩트 파일을 만들어 실행해도 뜨지 않네요 확인 한 번 부탁드립니다!

[FEAT] 선택지별 투표 결과 API 호출 시, 기권자 정보도 함께 조회

---

backend/src/main/java/ddangkong/facade/room/dto/RoomSettingResponse.java
backend/src/test/java/ddangkong/documentation/room/RoomDocumentationTest.java

close #232 
- 카테고리 응답 방식이 '방 정보 조회 API' 와 '카테고리 조회 API' 둘이 서로 달라 통일 시켜줌
-  '방 정보 조회 API'에서 카테고리 응답을 단순 문자열에서 DTO로 변경

[FIX] 방 정보 조회 응답에 카테고리 DTO추가

---

backend/src/main/java/ddangkong/facade/room/balance/roomcontent/dto/RoomContentResponse.java
backend/src/test/java/ddangkong/controller/room/balance/roomcontent/RoomContentControllerTest.java
backend/src/test/java/ddangkong/documentation/room/balance/roomcontent/RoomContentDocumentationTest.java
backend/src/test/java/ddangkong/facade/room/balance/roomcontent/RoomContentFacadeTest.java

close #239 
- RoomContentResponse 에서는 Enum 을 그대로 받고 있어서 "ROMANCE"로 가고 응답하고 있었다
- RoomContentResponse 에서 Category의 표시 값인 "연애"를 보내주도록 수정

[FIX] RoomContentResponse 카테고리 응답 값 변경 #232

---

backend/src/main/java/ddangkong/service/room/balance/roomcontent/RoomContentService.java

#235 
애초에 Room이 Start하기 전에는 RoomContent가 0이기 때문에
게임 도중이 아닌, Ready상태인 Room에서 모든 멤버가 나가면 무조건 해당 에러 로그가 찍힌다.
```java
@Transactional
public void deleteRoomContents(Room room) {
List<RoomContent> roomContents = roomContentRepository.findAllByRoom(room);
roomContentRepository.deleteAllInBatch(roomContents);
if (room.getTotalRound() != roomContents.size()) {
log.error("방의 총 라운드와 방 컨텐츠 개수가 일치하지 않습니다. roomId: {}, totalRound: {}, roomContent 개수: {}",
room.getId(), room.getTotalRound(), roomContents.size());
}
}
```
해당 메서드의 log.error를 제거한다.

fix: 잘못된 에러 로그 제거 #235

---

backend/src/main/java/ddangkong/domain/room/RoomRepository.java
backend/src/main/java/ddangkong/facade/room/RoomFacade.java
backend/src/main/java/ddangkong/service/room/RoomService.java
backend/src/test/java/ddangkong/facade/room/RoomFacadeTest.java

close #246 
방 참여 가능 조회 API가 락을 통해 조회하는 메서드를 사용중이였다. 
- 방 참여 가능 조회 API가 락을 사용하지 않고 조회하도록 수정
- 유효하지 않는 방 ID로 요청이 예외가 아니라 false 를 리턴하도록 변경

[HOTFIX] 방 참여 가능 조회 API 수정

---

backend/src/main/resources/application-prod.yml

close #256 
Deprecated된 MySQL8 dialect설정을 최신 dialect 설정으로 변경한다. (근거 자료는 이슈 참조바랍니다.)
Deprecated된 `org.hibernate.dialect.MySQL8Dialect` 대신 `org.hibernate.dialect.MySQLDialect` 를 사용

[FIX] Deprecated된 dialect설정 제거 후 새로운 버전으로 변경

---

backend/src/main/java/ddangkong/aop/logging/DevRequestLoggingAspect.java
backend/src/main/java/ddangkong/aop/logging/ProdRequestLoggingAspect.java
backend/src/main/java/ddangkong/aop/logging/RequestLoggingAspect.java

#251
폴링 로깅을 하는 이유는 디버깅인데 해당 로깅을 prod, dev 두 환경에서 모두 수행할 필요가 없다고 판단하여
이를 리팩토링 대상으로 정의하였다.
운영 전 디버깅을 위한 환경은 Dev 환경이며, 때문에 폴링API에 대한 로깅은 Dev 환경에서만 수행하도록 설정한다고 생각이 들었다.
RequestLoggingAspect를 공통로직이 담긴 Abstract 클래스로 배치하고
이를 상속한 `DevRequestLoggingAspect` , `ProdRequestLoggingAspect` 를 생성하였다.
이에 `@Profile` 애노테이션을 붙여 
- `DevRequestLoggingAspect` 에선 **local, dev** 환경은 Polling API 로깅을 수행하고
- `ProdRequestLoggingAspect` 에선 **prod** 환경은 Polling API 로깅을 수행하지 않도록 처리하였다.
이를 통해 두 환경에 대한 역할을 명확히 분리하고 Prod 환경에서는 운영에 더 중요한 로그에 집중할 수 있도록 구현하였다.
- local, dev 환경은 Polling API인 `/api/balances/rooms/2/round-finished?round=1` 가 **로깅되는 것을 확인** 
- prod 환경은 Polling API인 `/api/balances/rooms/2/round-finished?round=1` 가 **로깅되지 않는 것을 확인**

[REFACTOR] Polling API dev환경에서만 로깅하도록 리팩토링

---

frontend/.storybook/preview.tsx
frontend/src/components/SelectContainer/SelectContainer.hook.ts
frontend/src/components/Timer/Timer.hook.ts
frontend/src/components/Timer/Timer.util.ts
frontend/src/components/common/RoomSettingModal/RoomSettingModal.test.tsx
frontend/src/components/common/RoomSettingModal/RoomSettingModal.tsx
frontend/src/constants/config.ts
frontend/src/constants/time.ts
frontend/src/hooks/useMyGameStatusQuery.ts
frontend/src/mocks/data/roomInfo.json
frontend/src/mocks/handlers/balanceContentHandler.ts
frontend/src/pages/GameResultPage/hooks/useCheckRoomReset.ts
frontend/src/pages/NicknamePage/NicknameInput/NicknameInput.styled.ts
frontend/src/pages/NicknamePage/NicknameInput/NicknameInput.tsx
frontend/src/pages/NicknamePage/NicknameInput/hooks/useNicknameInput.ts
frontend/src/pages/NicknamePage/NicknamePage.styled.ts
frontend/src/pages/NicknamePage/NicknamePage.tsx
frontend/src/pages/NicknamePage/useMakeOrEnterRoom.ts
frontend/src/pages/ReadyPage/useGetRoomInfo.ts
frontend/src/types/room.ts

#252 
- 닉네임 글자수 제한 없었음
- 확인 버튼으로만 이동 가능
- 정상 링크인데 에러 UI가 보여졌다가 사라짐
- 방 생성하는데 joinable API 요청 발생
- 닉네임 글자수 12자로 제한
- 닉네임 Enter로도 방 생성 및 참여 가능
- 잘못된 uuid로 판단하는 로직 수정
- 불필요한 joinable 요청 제거
버튼 위치 변경은 디자인적인 문제라 올릴지 말지 의견 코멘트 바람~!

[REFACTOR] 닉네임 설정 화면 UX 개선 및 리팩토링

---

backend/src/main/java/ddangkong/controller/exception/GlobalExceptionHandler.java
backend/src/main/java/ddangkong/exception/ClientErrorCode.java

Closed #265 
- Client에서 요청이 잘못된 상황까지 Discord 알람이 온다.
- HttpMediaTypeNotSupportedException, ClientAbortException을 400번대 에러로 처리
9/12 기준 dev, prod에서 온 알람 (SQL 관련 에러 제외)
```text
org.springframework.web.HttpMediaTypeNotSupportedException: Content-Type 'text/plain;charset=UTF-8' is not supported
```
해당 요청의 Content-Type을 지원하지 않는 것이므로 405 Method Not Allowed를 반환함
```text
org.apache.catalina.connector.ClientAbortException: java.io.IOException: Broken pipe
at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:341)
at org.apache.catalina.connector.OutputBuffer.flushByteBuffer(OutputBuffer.java:776)
at org.apache.catalina.connector.OutputBuffer.append(OutputBuffer.java:673)
at org.apache.catalina.connector.OutputBuffer.writeBytes(OutputBuffer.java:376)
at …
```

[FEAT] 500 에러가 아닌 에러 핸들링하기

---

.github/workflows/be-cd-prod-a.yml
.github/workflows/be-cd-prod-b.yml
.github/workflows/be-ci-prod.yml

#281 
Multi AZ 설정을 통한 API 서버 다중화 작업으로 SPOF(Single Point Of Failure)을 제거하여 HA(High Availability) 보장을 수행한다.
- 각 EC2에 Github Self-hosted Runner 설치 및 CI/CD 스크립트 수정
- CI/CD 스크립트에 분산 prod 환경 (prod-a, prod-b) 설정 적용
- CI는 prod-a 환경에서 수행
- (prod-b의 CD가 도는 동안 prod-a는 CI를 돌리느라 WAS가 닫히는 시간에 텀이 있기 때문에 DownTime이 짧아지는 효과가 있을 것으로 예상)

[FEAT] CI/CD 스크립트에 분산 prod 환경 (prod-a, prod-b) 설정 적용

---

backend/src/main/java/ddangkong/domain/room/balance/roomcontent/RoomContent.java
backend/src/test/java/ddangkong/domain/room/balance/roomcontent/RoomContentTest.java

close #302 
- 게임이 시작되었을 때 게임 준비 시간 3초가 주어지는데 1 라운드 종료 시간에 게임 준비 시간을 추가해주지 않어 게임이 투표 종료 설정 시간 전에 끝남
- 게임이 시작되었을 때 게임 준비 시간 3초가 주어지는데 1 라운드 종료 시간에 게임 준비 시간을 추가해주어야함

[FEAT] 첫 라운드에 게임 준비 시간 추가

---

frontend/src/components/common/a11yOnly/A11yOnly.styled.ts
frontend/src/components/common/a11yOnly/A11yOnly.test.tsx
frontend/src/components/common/a11yOnly/A11yOnly.tsx

#319 
스크린 리더 접근성 개선 회의에서, 시각적으로 숨겨져 있고 스크린 리더에서만 읽혀야 하는 요소들을 개별적으로 div에 스타일을 적용하는 방식은 직관적이지만, 코드가 복잡해지면 어떤 태그가 스크린 리더 전용인지 식별하기 어려워질 수 있다는 문제가 제기되었다.
이로 인해 가독성과 유지보수성을 고려했을 때, 이러한 요소들을 한눈에 파악하고 관리할 수 있는 A11yOnly 컴포넌트를 도입하는 것이 바람직하다는 의견이 모아졌다. 해당 컴포넌트를 통해 스크린 리더 전용 요소를 명확하게 정의하고, 코드의 일관성을 높이기로 결정했다.
타입 수준에서 기본값을 지정해주는 역할이며, `as` prop이 없을 때 기본적으로 span 타입으로 간주되도록 합니다. -> 컴파일 시 적용 !
컴포넌트를 렌더링할 때 `as`가 없는 경우 기본값인 'span' 태그로 렌더링 됩니다. -> 런타임 시 적용 !
라운드 결과 페이지에서 A11yOnly 컴포넌트를 적용한 예시를 보여드릴게요 👏
- 수정 전(리뷰 반영 전)
- 수정 후(리뷰 반영 후)
https://github.com/user-attachments/assets/ba17de0e-e3bd-44f5-9de8-e39aa9a0cbff
공통 컴포넌트를 만드는 것은 늘 고민이 많네요  .. 😎 혹시나 더 고려할 부분이나 궁금한 점은 없을까요 ?! 리뷰 남겨주시면 의논해서 반영해 볼게요 👏👏 
> …

[FEAT] 스크린 리더 공통 컴포넌트 생성 

---

backend/src/main/resources/application-dev.yml

#323 
- Dev 환경에서 dev-init.sql이 지워졌지만, application-dev.yml에는 dev-init.sql를 실행하도록 하여 오류가 남
- application-dev.yml의 설정에서 dev-init.sql를 실행 부분 제거

[FIX] application-dev.yml에는 dev-init.sql을 실행하지 않도록 수정

---

frontend/src/components/NicknameItem/NicknameItem.tsx
frontend/src/components/OptionParticipants/OptionParticipants.tsx
frontend/src/components/RoundResultTab/RoundResultTab.tsx
frontend/src/components/RoundVoteContainer/RoundVoteContainer.test.tsx
frontend/src/components/TabContentContainer/TabContentContainer.tsx
frontend/src/components/layout/Header/Header.stories.tsx
frontend/src/components/layout/Header/Header.tsx
frontend/src/pages/GamePage/GamePage.tsx

#325 
- 개선 전
https://github.com/user-attachments/assets/0334c3e8-72e6-49d0-91d4-e9812f06b6f0
```
📢
2 배너 랜드미크 
슬래시
5
투표 결과 머리말 레벨 1 앤드 배너
투표 통계 버튼 앤드 탐색 랜드마크
투표 현황 버튼 앤드 탐색
지금 20억 한꺼번에 받기 vs 죽을 때까지 매달 1000만원 받기
지금 20억 한꺼번에 받기
죽을 때까지 매달 1000만원 받기
100
%
0
%
2
명
0
명
땅콩 땅콩 유저 중
100
%
는
죽을 때까지 매달 1000만원 받기
를 선택했어요!
방장이 진행해 주세요 흐리게 표시 됨 버튼
```
- 문제점
1. 헤더의 정보를 끊어서 읽는다. 
2. 투표 통계와 투표 현황을 버튼으로 읽기 때문에 탭임을 인지하지 못한다.
3. 투표 통계를 끊어서 읽는다. 
4. 전체 땅콩 유저 투표 통계 요약을 끊어서 읽는다.
https://github.com/user-attachments/assets/b1093121-bfed-448d-9bc7-ad5cb768e8d6
```
📢
투표 현황 버튼 앤드 탐색
지금 20억 한꺼번에 받기 vs 죽을 때까지 매달 1000만원 받기
지금 20억 한꺼번에 받기 
콜론
2
사용자 이미지
엉뚱한 염소
사용자 이미지
웃긴 참새
죽을 때까지 매달 1000만원 받기
콜론
0
명
투표에 참여하지 않으셨어요
콜론
0
명
```
- 문제점
1. 선택지와 투표 인원 정보를 끊어서 읽고, 불필요한 텍스트까지 읽는다.
- 개선 후 …

[REFACTOR] 라운드 결과 페이지 스크린 리더 개선

---

backend/src/main/java/ddangkong/domain/room/RoomSetting.java
backend/src/main/java/ddangkong/exception/ClientErrorCode.java
backend/src/main/java/ddangkong/exception/room/InvalidTimeLimitException.java
backend/src/test/java/ddangkong/controller/room/balance/roomvote/RoomBalanceVoteControllerTest.java
backend/src/test/java/ddangkong/domain/room/RoomSettingTest.java
backend/src/test/java/ddangkong/facade/room/RoomFacadeTest.java
backend/src/test/java/ddangkong/facade/room/balance/roomvote/RoomBalanceVoteFacadeTest.java

Closed #331 
- 프론트 행님들이 스크린 리더 개선하는데 15초는 플레이 타임이 짧음
- 30초, 60초 설정 추가 필요
- 방의 게임 시간 설정을 10 15 30 60로 변경
- RoomSetting 관련 테스트 일부 추가

[FEAT] 방 게임 진행 시간 변경

---

backend/src/main/java/ddangkong/aop/logging/ControllerLoggingAspect.java
backend/src/main/java/ddangkong/aop/logging/ProdControllerLoggingAspect.java
backend/src/main/resources/logback-dev.xml
backend/src/main/resources/logback-prod.xml

#355 
#355 
이슈 참조 부탁드립니다.
해결방안으로 떠올린 방법은 **MDC**를 사용하는 것이다.
요청이 도착했을 때, 각 요청마다 **TraceID(UUID)** 를 생성하고, **MDC**에 삽입한다.
그리고 Log를 찍을 때 해당 정보를 함께 표시해준다.
그럼 요청별로 구분하는 것이 굉장히 쉽게 변할 것이라고 생각했다.
**MDC**는 주로 로그 관리에서 사용하는 개념으로, **스레드 로컬(Thread Local)** 변수를 통해 각 스레드별로 고유한 컨텍스트 데이터를 저장하고,
이를 로그에 포함시키는 기능을 제공한다.
스프링 부트와 같은 환경에서 요청 단위로 고유한 **TraceID**를 생성해 로그에 삽입할 때 자주 사용된다.
**[MDC의 주요 기능]**
- **스레드별로 독립된 데이터**를 관리할 수 있습니다. 이는 특히 **멀티스레드** 환경에서 유용하다.
- 특정 요청이나 작업에 관련된 메타데이터를 로그에 자동으로 삽입할 수 있다. 예를 들어, `TraceID`, 사용자 ID, 세션 ID 등과 같은 정보를 로그 메시지에 포함할 수 있다.

[REFACTOR] 다중 서버 환경에서 Logging의 Observability 개선하기

---

frontend/src/components/RoomSetting/RoomSetting.tsx
frontend/src/components/common/Dropdown/Dropdown.stories.tsx
frontend/src/components/common/Dropdown/Dropdown.styled.ts
frontend/src/components/common/Dropdown/Dropdown.tsx
frontend/src/components/common/Modal/Modal.styled.ts
frontend/src/components/common/RoomSettingModal/CategoryDropdown/CategoryDropdown.tsx
frontend/src/components/common/RoomSettingModal/RoomSettingContainer/RoomSettingContainer.styled.ts
frontend/src/components/common/RoomSettingModal/RoomSettingContainer/RoomSettingContainer.tsx
frontend/src/components/common/RoomSettingModal/RoomSettingModal.test.tsx
frontend/src/components/common/RoomSettingModal/RoomSettingModal.tsx
frontend/src/styles/GlobalStyle.ts

#352 
https://github.com/user-attachments/assets/ad5b1b73-25cc-43a1-ab20-0fd90d09980a
1. 어떤 선택 목록인지 알 수 없다.
2. 목록이 열려있고 스와이프 했을 때 요소로 넘어가지 못한다. 
3. 목록 중 몇 번째인지 알 수 없다.
4. 목록 중 어느 것이 선택되어 있는지 알 수 없다. 
5. 선택 후 포커스를 잃는다.
1. 어떤 설정 값이 선택되어 있는지 알 수 없다. 
2. 몇 개의 목록 중 몇 번째인지 알 수 없다.
https://github.com/user-attachments/assets/274c8a2d-36e9-42ba-9709-3d700e3bd27b
> 📢 카테고리 선택 목록, 현재 선택: 연애, 팝업 버튼, 상자 팝업, 피커를 활성화 하려면 이중탭 하십시오.
> 📢 카테고리 선택 목록 -> 연애 -> 만약에 -> MBTI -> 음식
> 📢 연애 목록 시작 -> ... -> 음식 목록 끝
> 📢 선택됨 음식
> 📢 5 선택 버튼 선택됨
> 📢총 3개 중 1번째
해당 자료들을 참고하였습니다 ✨
https://nuli.navercorp.com/community/article/1133219
https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-select-only/

[REFACTOR] 방 설정 모달 접근성 개선 및 제한 시간 추가 반영

---

backend/src/main/resources/logback-prod.xml

#359 
Loki에서 로그 정보를 수집하여 Grafana에서 확인할 수 있기 때문에 운영환경에서 log를 자주 열람하지 않는다.
때문에 하루가 지난 로그는 gz 형태로 구성하여 저장공간을 절약한다.
> dev 환경은 스프린트에서 개발을 진행하며 자주 열람하기도 하고, 스프린트 단위인 2주 단위로 제거되므로 압축설정을 하지 않는다.
일자가 지난 로그는 `gz`으로 압축하여 관리

[FEAT] 하루 지난 로그 gz으로 압축하여 관리

---

frontend/src/components/GameResult/GameResult.hook.ts
frontend/src/components/StartButtonContainer/StartButton/hooks/useGameStart.ts
frontend/src/components/TopicContainer/TopicContainer.test.tsx
frontend/src/components/common/ErrorFallback/AsyncErrorFallback/AsyncErrorFallback.tsx
frontend/src/components/common/ErrorFallback/RouterErrorFallback/RouterErrorFallback.tsx
frontend/src/components/common/QueryClientDefaultOptionProvider/QueryClientDefaultOptionProvider.tsx
frontend/src/components/common/SelectButton/SelectButton.hook.ts
frontend/src/constants/message.ts
frontend/src/pages/MainPage/useCreateRoom.ts
frontend/src/pages/NicknamePage/useMakeOrEnterRoom.ts
frontend/src/router/HeaderLayout.tsx
frontend/src/router/index.tsx
frontend/src/types/error.ts
frontend/src/utils/test-utils.tsx

#358 
- 똑같은 에러 핸들링 로직인데 중복해서 사용하고 있었음
- 다른 mutation에 대해서도 같은 에러 처리인데 처리되지 않고 있었음
- 쿠키 로직이 추가되면서 쿠키 관련 에러 핸들링이 안되고 있었음
- 공통 에러 핸들링 로직을 setDefaultOptions를 이용해 queryClient에서 처리
- 쿠키 에러 코드 및 에러 메시지 추가
queryClient 에서 똑같은 로직으로 처리되는 에러 핸들링 로직들을 묶었습니다.
가장 어려웠던 부분은 Modal 에서도 QueryClient가 필요하고, QueryClient 에서도 Modal 이 필요한 모순적인 상황이였습니다.
방설정 모달에서 invalidateQueries를 하기 위해 QueryClient가 부모에 있어야 하고, QueryClient에서 공통 에러 핸들링 로직을 묶기 위해 Modal이 부모에 있어야 했습니다.
이러한 문제를 그려봤을 때 QueryClient는 무조건 Modal보다 부모에 있어야 한다고 판단했고, Modal 하위에서 공통 에러 핸들링 로직을 묶는 방법을 찾아봤습니다.
Tkdodo님 블로그를 봤을 땐 QueryCache를 사용하여 공통 로직을 분리하는 것을 권장했는데, QueryCache는 QueryClient를 생성할 때만 주입할 수 있어서 `setDefaultOptions` 로 처리하였습니다.
또한 테스트 케이스에서 억까(?)를 당했는데 retry가 false가 아닐 경우 에러 폴백이 안뜨는 문제가 있었습니다. 해당 문제는 기존 옵션이 덮어씌워지면서 문제가 발생했다는 걸 알게 되었습니다!!!!
하지만 프로덕션 환경에서까지 …

[REFACTOR] 에러 핸들링 공통 로직 개선 및 쿠키 에러 핸들링

---

frontend/src/components/OptionParticipants/OptionParticipants.tsx
frontend/src/components/ReadyMembersContainer/ReadyMembersContainer.tsx
frontend/src/components/SelectContainer/SelectContainer.test.tsx
frontend/src/components/SelectContainer/SelectContainer.tsx
frontend/src/components/SelectContainer/Timer/Timer.tsx
frontend/src/components/SelectContainer/Timer/Timer.util.ts
frontend/src/components/SelectOption/SelectOption.tsx
frontend/src/components/common/SelectButton/SelectButton.tsx
frontend/src/components/common/a11yOnly/A11yOnly.tsx
frontend/src/components/layout/Header/Header.styled.ts

#361 
1. role="text"는 표준으로 정의되어 있지 않은 속성인데 임의로 사용하고 있다. 
2. 몇 가지 컴포넌트에서 접근성 코드의 개선이 필요하다. 
> status가 아니라 alert를 사용한 이유는 1) 매 초 남은 시간을 안내하는 것이 아니라 제한 시간 시작, 중간, 5초 남았을 때에 안내하기 때문이다. 2) 선택지를 **제한 시간**안에 골라야 하기 때문에 긴급한 알림이라고 판단하였다.  
> 두 개 중 하나를 선택하는 것이라 라디오의 성격을 가진다고 생각했다. 
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/alert_role
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/status_role
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/radio_role

[REFACTOR] 접근성 컴포넌트 A11yOnly 리팩토링 및 추가 접근성 코드 리팩토링

---

backend/src/docs/asciidoc/room.adoc
backend/src/main/java/ddangkong/config/CorsConfig.java
backend/src/main/java/ddangkong/controller/room/RejoinCookieEncryptor.java
backend/src/main/java/ddangkong/controller/room/RoomController.java
backend/src/main/java/ddangkong/controller/room/RoomMemberCookieEncryptor.java
backend/src/main/java/ddangkong/facade/room/RoomFacade.java
backend/src/main/java/ddangkong/facade/room/dto/RoomMemberResponse.java
backend/src/test/java/ddangkong/controller/room/RoomControllerTest.java
backend/src/test/java/ddangkong/controller/room/RoomMemberCookieEncryptorTest.java
backend/src/test/java/ddangkong/documentation/room/RoomDocumentationTest.java
backend/src/test/java/ddangkong/facade/room/RoomFacadeTest.java

close #357 
- 프론트엔드에서 쿠키를 헤더에 담아서 요청을 보내려면 SameSite설정을 변경해야한다.
- 멤버 정보를 조회하는 API가 rejoin이여서 혼란이 옴
- SameSite설정을 변경
- rejoin 에서 member 로 URI 변경
RoomMemberResponse는 RoomJoinReponse와 필드가 동일하지만 서로 응답하고자 하는바가 다르다고 생각하여 RoomMemberResponse를 추가했습니다.

[FIX] 쿠키 설정 변경 

---

frontend/src/components/layout/Header/hooks/useExit.ts

#372 
방 나가기 API 호출 시 URL parameter가 memberId가 들어가지 않는 상황
memberId를 불러올 오는 부분은 수정해 URL parameter에 memberId가 들어가도록 수정

[FIX] 방 나가기 버그 수정 

---

backend/src/docs/asciidoc/room.adoc
backend/src/main/java/ddangkong/controller/room/RoomController.java
backend/src/main/java/ddangkong/controller/room/RoomMemberCookieEncryptor.java
backend/src/test/java/ddangkong/controller/room/RoomControllerTest.java
backend/src/test/java/ddangkong/documentation/room/RoomDocumentationTest.java

close #371 
- 방을 나갈 때 쿠키가 삭제되지 않았음
- 방 나갈 때 max-age를 0으로 설정하여 쿠키 삭제

[FIX] 방 나갈 때 쿠키 삭제 추가

---

frontend/src/components/RoomSetting/RoomSetting.styled.ts

#375
모바일 방 설정 컴포넌트 화면 깨지고 있음 
모바일 방 설정 컴포넌트 화면 깨지지 않게 수정
- 개선 전 
- 개선 후

[FIX] 모바일 방 설정 컴포넌트 화면 깨짐 해결 

---

backend/src/main/java/ddangkong/domain/room/member/Member.java
backend/src/main/java/ddangkong/exception/ClientErrorCode.java
backend/src/main/java/ddangkong/exception/room/member/InvalidNicknameException.java
backend/src/test/java/ddangkong/domain/room/member/MemberTest.java

#383 
닉네임 길이 검증을 1자부터 12자로 설정해야한다.
이때 Null, Blank 등에 대한 제한도 함께 수행하도록 검증로직을 변경해야한다.
- 닉네임 정책 `2~12자` -> `1~12자` 로 변경
- 공백, Null 제한 설정

[REFACTOR] Nickname 검증 규칙 수정

---

backend/src/main/java/ddangkong/aop/logging/ControllerLoggingAspect.java

Closed #393 
- 현재 클래스의 Prefix를 통해서 메서드 대상을 관리 (ex. `execution(* ddangkong.controller..*Controller.*(..))`)
- 네이밍 컨밴션을 모두 인지하고 있어야 한다는 인지 비용 발생
- 클래스의 어노테이션(`@RestController`)을 통해 관리하도록 수정
- 컨트롤러에 필수적으로 사용되므로 따로 인지비용 없이 바로 사용될 수 있다.
- `@Pointcut` 내부 내용 수정
- [Effective Java 39. 명명 패턴보다는 어노테이션을 사용하라](https://be-study-record.tistory.com/82)

[REFACTOR] ControllerLoggingAspect 리팩토링

---

backend/src/main/java/ddangkong/facade/room/RoomFacade.java
backend/src/main/java/ddangkong/facade/room/balance/roomvote/RoomBalanceVoteFacade.java
backend/src/main/java/ddangkong/facade/room/balance/roomvote/context/VoteContext.java
backend/src/main/java/ddangkong/facade/room/balance/roomvote/dto/VoteFinishedResponse.java
backend/src/main/java/ddangkong/facade/room/dto/InitialRoomResponse.java
backend/src/main/java/ddangkong/facade/room/dto/RoundFinishedResponse.java
backend/src/test/java/ddangkong/controller/room/RoomControllerTest.java
backend/src/test/java/ddangkong/documentation/room/RoomDocumentationTest.java
backend/src/test/java/ddangkong/documentation/room/balance/roomvote/RoomBalanceVoteDocumentationTest.java
backend/src/test/java/ddangkong/facade/room/RoomFacadeTest.java
backend/src/test/java/ddangkong/facade/room/balance/roomvote/RoomBalanceVoteFacadeTest.java

Closed #394 
- 현재 모든 폴링 요청에서 "현재 방의 마스터 정보"를 제공해 주고 있었음
- 이전 버전에서 "방장 뷰"와 "일반 참여자 뷰"를 구분하기 위한 정보로 사용
- 더 이상 해당 정보가 (방 정보 조회를 제외한) Polling 요청에서 필요하지 않음
- 현 버전에서는 "내 정보 조회 API"의 캐싱을 사용하여 자신의 정보를 조회함
- 해당 정보는 코드 및 쿼리 등에서 리소스를 잡아 먹기 때문에 제거 필요
- (방 정보 조회를 제외한) Polling 요청에서 마스터 정보 제거
- 라운드 종료 조회 API
- 투표 종료 조회 API
- 방 초기화 조회 API
- 관련 회의 자료
- 부수적으로 다루었습니다~
- https://www.notion.so/ghenmaru/TF-6e4d7119b7214ee0aec998d474147b61

[REFACTOR] Polling에서 사용하지 않는 바디 정보 제거

---

frontend/jest.config.json
frontend/src/mocks/worker.js
frontend/src/pages/GamePage/components/SelectContainer/Timer/Timer.test.tsx
frontend/src/pages/GamePage/components/SelectContainer/Timer/hooks/timerWorker.ts
frontend/src/pages/GamePage/components/SelectContainer/Timer/hooks/useTimer.ts

#403 
- 다른 탭으로 이동하여 서비스를 백그라운드로 실행 시 타이머가 느려지는 현상 발생
- 타이머가 느려질 경우, 타이머 숫자가 0이 되기 전에 게임이 끝나 사용자 경험에 악영향
- Web Worker를 사용하여 독립적인 worker thread에서 타이머 계산 로직 동작
- 탭이 전환되어 리소스 우선순위가 밀려 실행이 느려지는 문제를 worker를 통해 해결
- 기존의 타이머 오차 일부 개선 (2~30ms -> 5ms)
기존에 setInterval만 사용했을 때는 메인 스레드에서만 동작하기 때문에 브라우저의 우선순위에 밀려 콜백 함수의 실행 또한 밀린 것을 확인할 수 있었습니다.
하지만 모바일 특성상 탭을 전환하는 경우가 많은데, 이때 타이머가 밀리면서 0초가 되지 않았는데 게임이 종료되는 현상이 발행하게 됩니다. 이는 사용자 경험에 좋지 않으므로 web worker를 사용하여 독립적인 스레드에서 타이머를 계산하도록 개선하였습니다. 이를 통해 탭을 전환하더라도 타이머가 일정하게 유지되는 것을 확인할 수 있습니다.
| ❌ worker 적용 전 탭 전환 시 타이머 | ✅ worker 적용 후 탭 전환 시 타이머 |
|:-:|:-:|
|<img alt="image" src="https://github.com/user-attachments/assets/53b9ca0d-7a27-4618-bbc9-7058873c3b68">|<img alt="image" src="https://github.com/user-attachments/assets/01e35a9c-7d1a-4a2c-89df-572883f80c28">| …

[REFACTOR] 탭 전환 시 발생하는 타이머 오차를 Web Worker를 활용하여 사용자 경험 개선

---

.github/workflows/be-cd-dev.yml
.github/workflows/be-ci-dev.yml
backend/scripts/dev/health-check.sh
backend/scripts/dev/kill-application.sh
backend/scripts/dev/replace-new-version.sh

#416 
우테코 수료에 따라 만료되는 기존 AWS 계정.
새로운 AWS 계정을 생성하여 새 Dev 환경 구축

[FEAT] 새로운 AWS 계정에서 Dev 환경 CI/CD 구축

---

.github/workflows/fe-d-n-label-automation.yml

#422 
- 비대면으로 소통하다보니 코드 리뷰가 지연되어 병목 발생
- 오전 12시에 스크립트 동작(카운팅) + 주말 제외 3일
- ex) "D-3" 라벨이였다면 스크립트 동작 후에는 "D-2" 라벨로 변경
- 라벨 설정을 안했을 경우 PR 포함 3일이니 밤 12시에는 "D-2" 라벨 설정
- 이유: 알림보단 미리 카운팅 필요. 새벽에 작업하는 경우 많음. 주말은 쉬자.
- **D-0일 때 머지 조건 제거 X → branch 단위로 제거하는 것밖에 없음**
- D-0 인 PR 1개만 있어도 branch rule이 제거되는 건 위험하다고 판단.
- **D-0이 되면 PR 작성자가 without review 버튼을 통해 머지하기.**
노션 논의 사항 정리

[REFACTOR] D-n 라벨 자동화 스크립트를 통한 코드 리뷰 병목 개선

---

.github/workflows/fe-review-reminder.yml

#424 
비대면 작업 또는 여러 일정을 병행하는 경우 코드 리뷰를 하지 않은 PR을 잊는 경우가 생겨 코드 리뷰 병목 현상이 발생했습니다.
코드 리뷰를 리마인드하는 스크립트를 작성하여 디스코드 알림과 연동하도록 합니다.
알림 형식은 다음과 같습니다.
- 열려 있는 PR 중 FE라벨이 달린 PR이 없으면 알림을 발송하지 않는다.
- 열려 있는 PR 중 FE라벨이 달린 PR이 있으면 평일 오전 11시에 스크립트를 실행하여 알림을 발송한다.
- 여러 PR이 있는 경우 D-DAY에 근접한 순서대로 정렬한다.
- approved 상태를 제외한 상태인 리뷰어는 알람을 받고, approved 상태인 리뷰어는 해당 PR의 알람을 받지 않는다.  
- 리뷰어는 가장 최신 상태로 안내한다. 또한 PR 작성자는 제외한다.
- 리뷰어로 지정된 모두가 approved 상태이면 assignees에게 코멘트를 확인하고 머지에 대해 안내한다. 
- 해당 PR에서 수정이 일어났는지 확인하기 위해 생성일과 마지막 수정일을 안내한다. -> 알림이 길어지는 문제, 자신이 리뷰 후에 수정된 것인지 여전히 판단하기 힘들다는 의견 반영하여 삭제.
알림 예시 (초기 버전)
```
🍀 [FE] 오늘의 PR 리뷰 목록 🍀
마감일: [D-0] 
제목: [REFACTOR]: 로그인 이슈 해결
현황: @마루(requested changes), @포메(comment), @썬데이(not started)
생성일: 2024-11-08 10:00:00
마지막 수정: 2024-11-10 15:20:00
링크: …
```

[FEAT] PR 리뷰 리마인더 및 Discord 알림 워크플로우 생성

---

backend/src/main/java/ddangkong/domain/balance/content/BalanceContent.java
backend/src/main/java/ddangkong/domain/balance/content/Category.java
backend/src/main/java/ddangkong/domain/room/RoomSetting.java

Closed #435 
- MySQL에서 카테고리를 ENUM으로 관리하다보니, 카테고리가 추가될 때마다 MySQL에서 관리하는 ENUM 필드의 허용 값을 변경해주어야 함
- MySQL에서 카테고리를 ENUM 대신 VARCHAR(20)으로 관리
- Application에서는 java enum으로 관리
- 개발자 카테고리 추가
- 문서화 추가 예정

[REFACTOR] MySQL에서 카테고리를 ENUM 대신 VARCHAR(20)으로 관리

---

frontend/src/apis/balanceContent.ts
frontend/src/constants/url.ts
frontend/src/pages/GamePage/components/SelectContainer/GameVoteStatusContainer/GameVoteStatusContainer.styled.ts
frontend/src/pages/GamePage/components/SelectContainer/GameVoteStatusContainer/GameVoteStatusContainer.tsx
frontend/src/pages/GamePage/components/SelectContainer/SelectContainer.tsx
frontend/src/pages/GamePage/components/SelectContainer/hooks/useVoteIsFinished.ts
frontend/src/pages/GamePage/components/SelectContainer/hooks/useVoteIsFinishedQuery.ts
frontend/src/pages/ReadyPage/components/StartButtonContainer/hooks/useCountdown.ts
frontend/src/styles/Theme.ts
frontend/src/styles/emotion.d.ts

- 게임 화면 중 현재 투표 상태를 알았으면 좋겠다는 피드백이 있었음
- 선택을 누르지 않아도 선택이 되도록 이미 구현이 되어있는데, 구현을 해달라는 피드백이 있었음
- 게임 화면에서 멤버별 투표 여부를 API Response에 추가하여 누가 투표했는지 확인
- 버튼에 추가하는 대신 빈 공간에 `"0명 중 0명이 투표했어요!"` 텍스트로 **현재 투표 상태 알려주기**
- 기획 변경 이유(1): 버튼에 선택 (0/1 명) 으로 두려고 했으나, 서비스를 잘 모르는 사람 입장에선 이해하기 어렵다고 판단
- 기획 변경 이유(2): 실제로 팀원이 아닌 사람한테 물어봤을 때 설명없이 이해하기 어려웠다고 하여 변경
- 사용자 입장에선 선택된 옵션으로 투표된다는 기능이 있는걸 모르고, 꼭 선택을 눌러야된다고 생각할 것 같다.
- 모두 투표를 완료하면 빠르게 투표가 종료된다는 텍스트를 추가하여 사용자에게 알린다.
|❌ before | ✅ after |
|:-:|:-:|
|<img src="https://github.com/user-attachments/assets/0bace0a1-a090-45cd-9067-f57990986ff8">|<img src="https://github.com/user-attachments/assets/7f40dc46-4b52-4435-84a5-1d47c2ffae3c">|
게임 폴링 API 응답값으로 투표 인원과 전체 인원을 가져옵니다. 그런데 네트워크가 느릴 경우를 대비하여 방어 코드를 작성해야 합니다.
근데 "0명 중 0명", "-명 중 -명", "로딩중" 등으로 하려고 했지만 응답이 느리다면 …

[FEAT] 사용자 피드백을 반영하여 게임 화면에서 멤버별 투표 현황 보여주기

---

.github/workflows/fe-d-n-label-automation.yml
.github/workflows/fe-review-reminder.yml

#432 
리마인더 스크립트에서 여러 수정이 필요했고, 이유와 변경 사항은 아래에 설명해 두었습니다. 
https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule
공식 문서에 따르면 정각에는 과부화가 발생할 수 있다고 하여 11시 정각에 실행되었던 스크립트를 10시 10분으로 수정하였습니다 ! 딜레이 문제가 사라지는 지는 머지 후에 확인할 수 있을 것 같아요 🥹

[FIX] 프론트엔드 코드 리뷰 리마인더 및 Discord 알림 수정

---

backend/src/docs/asciidoc/room.adoc
backend/src/main/java/ddangkong/controller/room/RoomController.java
backend/src/main/java/ddangkong/domain/room/member/Member.java
backend/src/main/java/ddangkong/exception/ClientErrorCode.java
backend/src/main/java/ddangkong/exception/room/member/AlreadyCommonException.java
backend/src/main/java/ddangkong/facade/room/RoomFacade.java
backend/src/main/java/ddangkong/facade/room/dto/PassMasterRequest.java
backend/src/main/java/ddangkong/service/room/member/MemberService.java
backend/src/test/java/ddangkong/controller/room/RoomControllerTest.java
backend/src/test/java/ddangkong/documentation/room/RoomDocumentationTest.java
backend/src/test/java/ddangkong/domain/room/member/MemberTest.java
backend/src/test/java/ddangkong/facade/room/RoomFacadeTest.java
backend/src/test/java/ddangkong/service/room/member/MemberServiceTest.java

closed #473 
- 대기실에서 방장을 다른 사람에게 넘겨주는 기능 필요
- 구현 사항
- 방장 넘기기 도메인 로직 구현
- 방장 넘기기 API 구현
- 방장 넘기기 Docs 작성
- 중요 로직
- `nextMasterId` 가 이미 방장인 경우, 400 에러 발생
- 방이 READY 상태가 아닌 경우, 400 에러 발생
- 오랜만에 PR 쓰니까 진짜 추억 돋는다.
- 일단 타칸 리뷰는 필수적으로 받고, 프린이나 이든 리뷰는 선택적으로 받을께요~
- 타칸이 빠르게 Approve 하면 그냥 머지 되는겁니다~

[FEAT] 방장 넘기기 API 구현

---

backend/src/main/java/ddangkong/facade/room/dto/RoomInfoResponse.java
backend/src/test/java/ddangkong/facade/room/RoomFacadeTest.java

closed #476 
- 이전에는 DB 저장 로직, 방장 전달 로직 기능 구현에 의해 방장이 항상 먼저 조회되었음
- '방장 넘기기' 기능이 들어오면서 방장이 맨 위에 있지 않는 경우가 생김
- `RoomInfoResponse`의 매핑 로직 중 정렬 기능 추가
- 관련 테스트 케이스 추가
- 간단하게 구현했습니다.

[FIX] 방 정보 조회 API (polling)에서 방장이 항상 제일 앞에 있도록 구현

---

backend/scripts/dev/kill-application.sh
backend/scripts/dev/replace-new-version.sh
backend/src/main/java/ddangkong/controller/room/RoomController.java
backend/src/main/java/ddangkong/domain/room/member/Member.java
backend/src/main/java/ddangkong/exception/ClientErrorCode.java
backend/src/main/java/ddangkong/exception/room/InvalidImageUrlException.java
backend/src/main/java/ddangkong/facade/balance/vote/dto/GiveUpVoteMemberResponse.java
backend/src/main/java/ddangkong/facade/room/RoomFacade.java
backend/src/main/java/ddangkong/facade/room/balance/roomvote/dto/OptionRoomBalanceVoteResponse.java
backend/src/main/java/ddangkong/facade/room/balance/roomvote/dto/RoomMemberVoteMatchingResponse.java
backend/src/main/java/ddangkong/facade/room/dto/RoomJoinRequest.java
backend/src/main/java/ddangkong/facade/room/member/dto/MemberResponse.java
backend/src/main/java/ddangkong/service/room/member/MemberService.java
backend/src/test/java/ddangkong/controller/room/RoomControllerTest.java
backend/src/test/java/ddangkong/controller/room/balance/roomvote/RoomBalanceVoteControllerTest.java
backend/src/test/java/ddangkong/documentation/room/RoomDocumentationTest.java
backend/src/test/java/ddangkong/documentation/room/balance/roomvote/RoomBalanceVoteDocumentationTest.java
backend/src/test/java/ddangkong/domain/room/balance/roomvote/RoomBalanceVoteRepositoryTest.java
backend/src/test/java/ddangkong/domain/room/member/MemberTest.java
backend/src/test/java/ddangkong/domain/room/member/RoomMembersTest.java
backend/src/test/java/ddangkong/facade/room/RoomFacadeTest.java
backend/src/test/java/ddangkong/facade/room/balance/roomvote/RoomBalanceVoteFacadeTest.java
backend/src/test/java/ddangkong/service/room/member/MemberServiceTest.java
backend/src/test/java/ddangkong/support/fixture/domain/MemberFixture.java

closed #484 
- 각 멤버가 특정 사진을 선택하는 기능 구현 예정
- 각 멤버 정보 요청/응답에서 멤버의 이미지 URL을 추가하여야 함
- Facade - Service 로직 개선
- 기존에는 멤버 생성시 서비스에서 nickname 만 받았으나, 이제는 Member 도메인 객체를 받도록 함
- Facade, Service 메서드 시그니처 변경으로 인한 테스트 수정
- 머지는 포메 작업 끝나면, 같이 진행할 예정

[FEAT] 멤버 정보 요청/응답에 이미지 URL 추가

---

backend/src/main/java/ddangkong/facade/room/dto/RoomJoinRequest.java

#492 
- FE 유저 별 이미지 설정 기능이 완성됨에 따라 `imageUrl` 기본값 제거 필요
- `RoomJoinRequest`에 있는 `imageUrl`의 기본값 제거

[REFACTOR] 이미지 URL 기본 값 제거
