frontend/package.json
frontend/src/apis/fetcher.ts
frontend/src/apis/question.ts
frontend/src/constants/url.ts
frontend/src/mocks/data/question.json
frontend/src/mocks/handlers/index.ts
frontend/src/mocks/handlers/questionHandler.ts
frontend/src/mocks/handlers/voteHandler.ts
frontend/tsconfig.json

#6 
API 호출 어려움
msw를 활용하여 mock server 구축

[FEAT] msw를 활용하여 mock server 구축

---

frontend/.gitignore
frontend/package-lock.json
frontend/package.json
frontend/src/App.tsx
frontend/src/components/GameResult/GameResult.styled.ts
frontend/src/components/GameResult/GameResult.tsx
frontend/src/components/NicknameList/NicknameList.styled.ts
frontend/src/components/NicknameList/NicknameList.tsx
frontend/src/components/SelectContainer/SelectContainer.tsx
frontend/src/components/SelectContainer/SelectCotainer.styled.ts
frontend/src/components/SelectOption/SelectOption.styled.ts
frontend/src/components/SelectOption/SelectOption.tsx
frontend/src/components/Timer/Timer.stories.ts
frontend/src/components/Timer/Timer.styled.ts
frontend/src/components/Timer/Timer.tsx
frontend/src/components/common/Button/Button.styled.ts
frontend/src/components/common/Button/Button.tsx

#5
스프린트 2차에 사용할 개별 컴포넌트가 없음
필요한 컴포넌트들 최소한의 mark-up만 한 상태로 작성

[FEAT] 2차 스프린트 P1 개별 컴포넌트 생성

---

frontend/src/App.tsx
frontend/src/apis/question.ts
frontend/src/components/GameResult/GameResult.styled.ts
frontend/src/components/GameResult/GameResult.tsx
frontend/src/components/NicknameList/NicknameList.styled.ts
frontend/src/components/RoundVoteResult/RoundVoteResult.styled.ts
frontend/src/components/RoundVoteResult/RoundVoteResult.tsx
frontend/src/components/SelectContainer/SelectContainer.styled.ts
frontend/src/components/SelectContainer/SelectContainer.tsx
frontend/src/components/SelectOption/SelectOption.styled.ts
frontend/src/components/SelectOption/SelectOption.tsx
frontend/src/components/Timer/Timer.styled.ts
frontend/src/components/TopicContainer/TopicContainer.styled.ts
frontend/src/components/TopicContainer/TopicContainer.tsx
frontend/src/components/layout/Content/Content.styled.ts
frontend/src/components/layout/Content/Content.tsx
frontend/src/components/layout/Header/Header.tsx
frontend/src/hooks/useQuestionQuery.ts
frontend/src/index.tsx
frontend/src/mocks/data/question.json
frontend/src/pages/GamePage/GamePage.tsx
frontend/src/pages/GameResultPage/GameResultPage.tsx
frontend/src/pages/RoundResultPage/RoundResultPage.styled.ts
frontend/src/pages/RoundResultPage/RoundResultPage.tsx
frontend/src/router/index.tsx
frontend/src/router/layout.tsx
frontend/src/styles/GlobalStyle.ts
frontend/src/types/question.ts
frontend/webpack.config.dev.js

로직과 컴포넌트가 흩어져 있는 상태
컴포넌트 조립 및 로직 추가

[FEAT] 라우터 및 msw 연결

---

.github/workflows/be-cd-dev.yml

#22 
- deploy sh 파일 실행 코드 오류가 존재했다. 파이프라인이 필요하지 않은데 존재하고 있었음.
- deploy sh 파일 실행 코드 오류 수정
- StrictHostKeyChecking=no 설정을 통해 호스트 키 체킹 과정 생략

fix: CD 스크립트 수정

---

.github/workflows/be-cd-dev.yml

#22 
deploy script 실행 코드가 self-hosted 형식 아닌 외부에서 요청하는 형식으로 작성되었다.
ec2 서버는 ssh 요청이 막혀있기 때문에 관련 코드를 모두 지우고 ec2의 deploy script 작동 로직만 수행하도록 변경하였다.

[FIX] deploy script 실행 코드 self-hosted 방식으로 변경

---

.github/workflows/be-cd-dev.yml

#22 
스크립트 수정 과정에서 job 스크립트 내부에 steps가 빠졌다.
job 스크립트 내부에 steps 를 추가하였다.

fix: job 스크립트 내부에 steps 추가 #22

---

.github/workflows/be-cd-dev.yml
.github/workflows/be-ci-dev.yml

#31 
현재 스크립트의 trigger path가 ./backend 패키지로 구분되어있어서 
최상위에 있는 .github 에 대한 변경 정보는 CI/CD 가 작동하지 않는다.
workflow_dispatch 설정을 통해 버튼으로 Actions에 있는 스크립트를 실행시킬 수 있도록 구현한다.

[FEAT] workflow_dispatch 설정

---

frontend/.husky/prepare-commit-msg

#41
husky 스크립트에서 이슈 번호를 붙일 때 줄 바꿈이 발생함 
줄 바꿈이 나오지 않도록 수정

[FIX]: husky 이슈 번호 줄 바꿈 제거 

---

backend/src/main/java/ddangkong/config/CorsConfig.java
backend/src/main/java/ddangkong/config/JpaAuditingConfig.java
backend/src/test/java/ddangkong/domain/BaseRepositoryTest.java
backend/src/test/resources/application.yml

close #57 
클라이언트와 브라우저 통신을 위해 서버에서 CORS 설정을 적용해야 한다.
- WebMvc CORS 설정 적용
- JPA auditing 설정 적용
> 연결된 이슈와 관계없으나, auditing 설정이 빠진 것을 발견하여 추가함
CORS origin은 환경마다 구별하기 위해 yml로 뺐습니다. `application-local.yml`에 추가해주세요

[FEAT] CORS 설정

---

.github/workflows/be-cd-dev.yml
backend/src/main/resources/sql/data-dev.sql

#61 
dev 환경에 데이터베이스 서버를 구축해서 dev서버를 정상 동작시켜야한다.
- EC2 2024-ddangkong-db-dev 인스턴스 실행
- db 인스턴스에 MySQL DB 서버 실행
- application-dev.yml 세팅 및 Actions.secrets, be-cd-dev 스크립트에 설정 로직 추가
- 그런데 프로퍼티 값을 외부에서, 특히 한 번 입력되면 읽어볼 수도 없는 Actions Secrets에서 관리하는 것은 실제 값을 또다른 곳에서 관리하도록 하기 때문에 유지보수성을 저하시킨다는 생각이 들어 좋은 관리 방법은 아니라고 생각됩니다!
이후에 SecretsManager 등을 통해 주요 환경변수 값만 외부에서 안전하게 관리하도록 변경하고,
yml 파일은 프로젝트에서 직접 가지고 있게 만들 계획이에요!
- dev 서버 애플리케이션 동작 로그 `~/dev-nohup.out` 파일에 남기도록 cd 스크립트 수정

[FEAT] dev환경 DB 서버 구축

---

frontend/src/apis/balanceContent.ts
frontend/src/components/GameResult/GameResult.hook.ts
frontend/src/components/GameResult/GameResult.tsx
frontend/src/components/GameResultItem/GameResultItem.tsx
frontend/src/components/OptionParticipantsContainer/OptionParticipantsContainer.tsx
frontend/src/components/RoundVoteContainer/RoundVoteContainer.styled.ts
frontend/src/components/RoundVoteContainer/RoundVoteContainer.tsx
frontend/src/components/SelectContainer/SelectContainer.styled.ts
frontend/src/components/SelectContainer/SelectContainer.tsx
frontend/src/components/TabContentContainer/TabContentContainer.stories.tsx
frontend/src/components/TopicContainer/TopicContainer.styled.ts
frontend/src/components/common/NextRoundButton/NextRoundButton.hook.ts
frontend/src/components/common/SelectButton/SelectButton.tsx
frontend/src/constants/queryKeys.ts
frontend/src/hooks/useBalanceContentQuery.ts
frontend/src/hooks/useCountAnimation.ts
frontend/src/hooks/useRoundVoteResultQuery.ts
frontend/src/mocks/data/roundVoteResultInitialValue.json

#82 
- 개발 서버에 API 요청하면서 파라미터가 안맞음
- 프론트 배포 서버에서 API 호출이 안됨
- API 호출파라미터 수정
- 프론트 배포 서버와 개발 서버 연동
- cloudfront 새로고침 문제 해결

[FIX] 배포 시 발생한 오류 해결

---

backend/Dockerfile
backend/src/main/java/ddangkong/config/ClockConfig.java
backend/src/main/java/ddangkong/domain/balance/room/RoomContent.java
backend/src/main/java/ddangkong/service/balance/vote/BalanceVoteService.java
backend/src/test/java/ddangkong/controller/balance/vote/BalanceVoteControllerTest.java
backend/src/test/java/ddangkong/service/balance/vote/BalanceVoteServiceTest.java
backend/src/test/java/ddangkong/support/config/TestClockConfig.java
backend/src/test/resources/init-test.sql

#96 
- 스프린트 3에 맞게 투표 시 투표가 가능한지에 대한 검증이 필요함
- 투표 요청 시 현재 시간이 투표 가능한지 검증하는 기능 추가
- 해당 검증이 잘 동작하는지 확인하기 위한 테스트 추가
- RoomContent 에 투표 가능 시간 필드 추가
- 충돌 방지를 위해 RoomContent isUsed 필드 추가

[FEAT] 투표 시 라운드 진행 검증 추가

---

frontend/index.html

#129 
사용자가 서비스를 이용하는지 알 수 없음
GA4(Google Analytics 4)를 활용하여 pageview, 어떤 페이지에 얼마나 머무는지를 확인할 수 있음
구글 로그인 후  구글 애널리틱스 확인 가능
https://analytics.google.com/analytics/web/?authuser=2#/p452867354/reports/intelligenthome?params=_u..nav%3Dmaui

[FEAT] GA4(Google Analytics 4) 연결

---

.github/workflows/fe-ci-dev.yml
frontend/src/components/CategoryContainer/CategoryContainer.stories.ts
frontend/src/constants/url.ts

#138
Github Actions가 동작하지 않음 
실행 환경을 self-hosted로 변경함

[FIX] Github Actions 환경 Self hosted로 변경

---

frontend/src/apis/room.ts
frontend/src/components/common/Button/Button.styled.ts
frontend/src/components/common/Button/Button.tsx
frontend/src/constants/url.ts
frontend/src/pages/NicknamePage/useMakeOrEnterRoom.ts
frontend/src/pages/ReadyPage/ReadyPage.tsx
frontend/src/pages/ReadyPage/useGameStart.ts
frontend/src/pages/ReadyPage/useGetRoomInfo.ts

#146 
게임 시작 API가 연동이 되어 있지 않은 상황이었음
게임 시작 API와 연동 후 방장이 게임 시작 버튼을 누르면 전원 게임 방으로 이동한다. 

[FEAT] 게임 시작 API 연동

---

backend/src/docs/asciidoc/room.adoc
backend/src/main/java/ddangkong/controller/balance/room/RoomController.java
backend/src/test/java/ddangkong/controller/balance/room/RoomControllerTest.java
backend/src/test/java/ddangkong/documentation/balance/room/RoomDocumentationTest.java

Closed #142 
- 게임 시작 API가 RestDocs에 반영이 되지 않음
- 게임 시작 API를 RestDocs에 반영
컨트롤러 메서드 및 컨트롤러 테스트 순서를 **사용자 요청 흐름 순서**로 변경

[TEST] 게임 시작 API RestDocs에 추가

---

.github/workflows/be-cd-dev.yml
backend/build.gradle
backend/src/main/java/ddangkong/aop/logging/Polling.java
backend/src/main/java/ddangkong/aop/logging/RequestLoggingAspect.java
backend/src/main/java/ddangkong/controller/balance/room/RoomController.java
backend/src/main/java/ddangkong/controller/balance/vote/BalanceVoteController.java
backend/src/main/java/ddangkong/controller/exception/GlobalExceptionHandler.java
backend/src/main/resources/logback-dev.xml

close #144 
- 애플리케이션 운영 중 이슈가 발생했을 때 이를 트래킹하기 위한 로깅 프레임워크 필요
- Presentation Layer Request Logging (AOP)
- Logback xml 설정
- DEBUG level 파일 적재
-  ERROR level discord notification

[FEAT] Logging 적용

---

.github/workflows/be-cd-dev.yml

close #156 
명령어를 개행할 때 백 슬래시(`\`)를 추가하지 않아 CD에서 오류 발생
- 백슬래시 추가

[FIX] CD 스크립트 오류 해결

---

backend/src/main/java/ddangkong/aop/logging/RequestLoggingAspect.java
backend/src/main/java/ddangkong/controller/balance/vote/BalanceVoteController.java
backend/src/main/java/ddangkong/domain/balance/room/RoomContent.java
backend/src/main/java/ddangkong/service/balance/vote/BalanceVoteService.java
backend/src/test/java/ddangkong/documentation/balance/vote/BalanceVoteDocumentationTest.java
backend/src/test/java/ddangkong/service/balance/vote/BalanceVoteServiceTest.java

close #158 
투표가 종료되지 않아도 투표 결과를 조회할 수 있는 문제 존재
- 이전 버전의 검증 로직 제거
- 투표가 종료되어야 투표 결과를 조회할 수 있도록 변경

[FIX] 투표 결과 조회 api 검증

---

backend/src/main/java/ddangkong/controller/exception/GlobalExceptionHandler.java

close #185
현재 MethodArgumentTypeMismatchException, MethodNotAllowedException 에러를 핸들링해주지 않아서
500에러로 처리되고 있다.
때문에 discord 500 error notification 채널에도 의미없는 로그가 쌓이고 있으며,
중요한 로그가 발생해도 묻힐 가능성이 높은 상태이다.
- MethodArgumentTypeMismatchException 에러 핸들링
- MethodNotAllowedException 에러 핸들링

[FEAT] 처리되지 못한 에러 핸들링

---

.github/workflows/be-cd-dev.yml
.github/workflows/be-cd-prod.yml
.github/workflows/be-ci-dev.yml
.github/workflows/be-ci-prod.yml
.github/workflows/fe-ci-dev.yml
backend/src/main/resources/application-prod.yml

close #192 
- prod 환경 CI CD가 구축되어 있지 않음
- CI yml 파일 추가
- CD yml 파일 추가

[FEAT] Backend Prod 환경 CI CD 구축

---

frontend/src/components/GameResult/GameResult.tsx
frontend/src/components/RoundResultTab/RoundResultTab.tsx
frontend/src/components/SelectContainer/SelectContainer.hook.ts
frontend/src/components/common/InfoModal/InfoModal.tsx
frontend/src/components/common/Modal/Modal.styled.ts
frontend/src/components/common/Modal/Modal.tsx
frontend/src/components/common/NextRoundButton/NextRoundButton.tsx
frontend/src/components/layout/Header/Header.tsx
frontend/src/hooks/useMyGameStatusQuery.ts
frontend/src/index.tsx
frontend/src/pages/GameResultPage/hooks/useCheckRoomReset.ts
frontend/src/pages/ReadyPage/ReadyPage.tsx
frontend/src/pages/ReadyPage/useGetRoomInfo.ts
frontend/src/styles/GlobalStyle.ts

[FIX] 4차 데모 QA 반영

---

frontend/src/components/ReadyMembersContainer/ReadyMembersContainer.styled.ts
frontend/src/components/ReadyMembersContainer/ReadyMembersContainer.tsx
frontend/src/components/common/Modal/Modal.styled.ts
frontend/src/components/layout/Header/hooks/useRoutePath.ts
frontend/src/pages/NicknamePage/NicknamePage.styled.ts
frontend/src/pages/NicknamePage/NicknamePage.tsx
frontend/src/pages/NicknamePage/useMakeOrEnterRoom.ts
frontend/src/pages/ReadyPage/ReadyPage.tsx
frontend/src/pages/ReadyPage/useGameStart.ts

[FIX] 4차 데모 QA 반영(2)

---

frontend/src/components/layout/Header/Header.styled.ts
frontend/src/index.tsx
frontend/src/pages/ReadyPage/ReadyPage.tsx
frontend/src/pages/ReadyPage/useGameStart.ts
frontend/src/router/index.tsx

[FIX] 4차 데모 QA 반영(3) 

---

frontend/src/apis/room.ts
frontend/src/constants/url.ts
frontend/src/mocks/handlers/roomHandler.ts
frontend/src/pages/NicknamePage/NicknamePage.styled.ts
frontend/src/pages/NicknamePage/NicknamePage.tsx

fix: 방 참여 불가 시 에러 UI 보여주기 #245

---

README.md

#259
- 서비스에 대한 소개글과 기능 소개가 없었음
- 서비스 소개 추가, 
- 소개글 개선점 반영 (구체적인 예시, 문제를 어떻게 해결하는지)
- 주요 기능 gif 추가
피드백 고고
https://github.com/woowacourse-teams/2024-ddangkong/blob/refactor/%23259/README.md

[REFACTOR] README 서비스 소개  및 기능 소개 추가

---

backend/build.gradle
backend/src/main/resources/application-prod.yml

#279 
ELB를 통한 로드 밸런싱 추가가 되면서 대상그룹에 대한 HealthCheck가 필요하게 되었다.

[FEAT] Spring Actuator를 통한 HealthCheck 기능 추가

---

.github/workflows/be-ci-prod.yml
backend/src/main/java/ddangkong/config/database/DataSourceConfig.java
backend/src/main/java/ddangkong/config/database/RoutingDataSource.java
backend/src/main/java/ddangkong/config/database/RoutingReplicas.java
backend/src/main/resources/application-prod.yml

#287 
SPOF(Single Point of Failure) 문제에 대한 방어책이 존재하지 않음
SPOF(Single Point of Failure) 문제 방어를 위한 DB 다중화 설정 수행

[FEAT] DB Replication 설정

---

frontend/webpack.config.dev.js
frontend/webpack.config.prod.js

#305 
프로덕션 환경에서 실행 시 CodeBuild에서 빌드가 멈춤
BundleAnalyzerPlugin 실행 시 터미널 멈추는 현상을 보고 문제 인식

[FIX] BundleAnalyzerPlugin 을 프로덕션 환경에서 실행 시 빌드가 멈추는 오류 해결

---

backend/src/main/java/ddangkong/domain/room/member/Member.java
backend/src/main/java/ddangkong/exception/ClientErrorCode.java
backend/src/main/java/ddangkong/exception/room/member/InvalidNicknameException.java
backend/src/main/java/ddangkong/facade/room/dto/RoomJoinRequest.java
backend/src/main/java/ddangkong/service/room/balance/roomvote/RoomBalanceVoteService.java
backend/src/test/java/ddangkong/controller/room/RoomControllerTest.java
backend/src/test/java/ddangkong/controller/room/balance/roomcontent/RoomContentControllerTest.java
backend/src/test/java/ddangkong/controller/room/balance/roomvote/RoomBalanceVoteControllerTest.java
backend/src/test/java/ddangkong/domain/room/member/MemberTest.java

close #314 
- 투표를 선택한 뒤 투표를 눌렀을 때, 그 시간이 투표 종료 시간과 동일한 경우 DataIntegrityViolationException 예외가 발생했었다.
- 닉네임 길이 검증이 없었다.
- DataIntegrityViolationException 예외가 발생했었다. 해당 예외를 커스텀 예외로 감싸서 처리하도록 변경하였다.
- 닉네임 길이 검증을 추가했다.

[FIX] 중복 투표 예외 처리 및 닉네임 길이 검증 추가

---

backend/build.gradle
backend/src/main/resources/application-prod.yml

#337 
- Actuator에 보안 설정이 안되어 있었음
- 모니터링을 위해 Prometheus 매트릭 설정이 필요

[FEAT] Prometheus 매트릭 수집을 위한 Actuator 설정

---

backend/src/main/resources/application-prod.yml

[FIX] Actuator endpoint 허용 설정

---

backend/src/main/resources/application-dev.yml
backend/src/main/resources/application-prod.yml

close #345 
설정 파일의 key 값이 변경되었는데 업데이트 되지 않아 문제 발생
변경된 key값이 적용되도록 설정 파일 변경

[FIX] Dev, Prod 설정 키 변경 #345

---

.github/workflows/nginx-port-forwarding.yml
.github/workflows/shutdown.yml

close #381 
- job 네이밍 컨벤션 불일치
- 강제 종료
- job 네이밍 변경
- 안전 종료

[REFACTOR] 무중단 배포 Github Action 스크립트

---

backend/src/main/java/ddangkong/controller/room/RoomController.java
backend/src/main/java/ddangkong/controller/room/RoomMemberCookieEncryptor.java

close #384 
쿠키 삭제를 위해 max-age를 설정하였다.
하지만 Path가 달라서 같은 쿠키로 인식하지 않아 지워지지 않았음
쿠키 설정치를 동일하게 하였다.
> the cookie is uniquely identified not just by it's name, but by it's other attributes as well (domain and path).([ref](https://coderanch.com/t/357128/java/setMaxAge-doesnt-delete-cookie))

[FIX] 쿠키 삭제 시 설정 일치

---

frontend/public/index.html
frontend/src/components/GameResultItem/GameResultItem.styled.ts
frontend/src/components/GameResultItem/GameResultItem.tsx
frontend/src/constants/config.ts
frontend/src/constants/message.ts
frontend/src/pages/NicknamePage/NicknameInput/NicknameInput.tsx
frontend/src/types/error.ts

#380 
- 매칭 결과 페이지에서 매칭 퍼센트가 85% 이상인 경우 순위와 프로필 이미지가 밀리는 문제
- og 이미지가 설정되지 않음
- 추가된 에러 코드가 반영되지 않음

[FIX] 6차 스프린트 QA반영

---

frontend/src/components/GameResultItem/GameResultItem.styled.ts

#390  
- 중복 코드로 인하여 오류 발생
- 중복 코드 삭제

[FIX] 6차 스프린트 QA 반영 2차

---

.github/workflows/fe-cd-dev.yml
.github/workflows/fe-cd-prod.yml

#414 
우테코 수료로 인하여 계속된 서비스 운영을 위해 AWS를 이관해야 하는 상황
깃허브 액션과 AWS의 s3와 cloudFront를 사용하여 자동 배포 환경을 구축

[FEAT] 프론트엔드 깃허브 액션 CD 스크립트 생성

---

.github/workflows/fe-cd-admin.yml
frontend-admin/src/apis/fetcher.ts

#463 
- admin cd s3 업로드 실패
- admin cd s3 업로드 성공

[FIX] admin cd 스크립트 테스트

---

backend/src/main/resources/application-dev.yml
backend/src/main/resources/application-prod.yml

Closed #459 
- Session을 설정한 쿠키가 정상작동하지 않음
- 서버 도메인과 다른 도메인을 이용하며, samesite option을 설정해주지 않아 발생함
- Cookie 설정 추가
- samesite를 none으로 설정
- secure를 true로 설정
- 간단한 설정 작업이므로 빠르게 머지하도록 하겠습니다.

[FIX] 어드민 세션 중 쿠키 설정 수정

---

frontend/public/mockServiceWorker.js

#466
개발 환경인 `http:dev.ddangkong.kr` 사이트에서 MSW 오류로 인해 접속이 되지 않는 상황 
MSW 설정을 초기화하였음. 

[FIX] 개발 환경에서 MSW 오류로 인해 웹사이트에 접속할 수 없는 상황 

---

.github/workflows/fe-cd-dev.yml

#466 
개발 배포 환경에서 MSW가 활성화 되어 서버와 연결이 되고 있는 상황
빌드 시 dev가 아닌 prod로 되게 github 스크립트를 변경하였음

[FIX] 개발 환경에서 MSW 오류로 인해 웹사이트에 접속할 수 없는 상황

---

.github/workflows/be-cd-dev.yml
backend/scripts/dev/health-check.sh
backend/scripts/dev/replace-new-version.sh

closed #470 
- AWS에 인프라를 구축하여 비용이 계속 발생하고 있었습니다.
- GCP로 이관하여 크래딧으로 인프라를 구축합니다.
설정이 크게 바뀐 부분은 없고 시크릿 파일은 노션에 업데이트 해두었습니다.

[FEAT] 개발환경 GCP 이관

---

frontend/src/apis/room.ts
frontend/src/components/layout/Header/Header.styled.ts
frontend/src/components/layout/Header/RoundResultHeader/RoundResultHeader.tsx
frontend/src/components/layout/Header/hooks/index.ts
frontend/src/components/layout/Header/hooks/useStopGameMutation.ts
frontend/src/constants/url.ts
frontend/src/hooks/useMyGameStatus.ts
package-lock.json

#483 
게임 화면에서 중간에 게임을 중단하는 기능이 필요하다는 피드백 반영 (게임 설정 수정 및 방장 권한을 넘기거나 새로운 참여 등이 필요한 경우)
원래 구현 상태에서 가장 자연스럽게 로직을 추가할 수 있는 방향이 라운드 결과 화면에서 게임 중단 api를 호출하고 바뀐 응답 값을 통해 페이지를 이동하도록 하는 것이었습니다.
현재 상황에 따른 응답값은 다음과 같습니다.
> isGameFinished=true, isRoundFinished=true => 게임 중단
> isGameFinished=true, isRoundFinished=false => 게임 종료
> isGameFinished=false, isRoundFinished=true => 라운드 종료
따라서 게임의 현황을 관리하는 useGameStatus 훅에서 stop api 호출 후 1초마다 오는 응답값에 따라 분기를 추가했습니다.
```ts
import { useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import useBalanceContentQuery from './useBalanceContentQuery';
import useMyGameStatusQuery from './useMyGameStatusQuery';
import { ROUTES } from '@/constants/routes';
interface UseMyGameStatusProps {
roomId: number;
}
const useMyGameStatus = ({ roomId }: …
```

[FEAT] 게임 중단 기능 구현

---

frontend/src/components/layout/Header/Header.tsx
frontend/src/pages/NicknamePage/components/ImageList/ImageList.styled.ts
frontend/src/pages/NicknamePage/components/ImageList/ImageList.tsx
frontend/src/pages/NicknamePage/hooks/useAccessRoom.ts

#494 
이미지가 flex + flex-wrap 방식으로 구현되어 있어. 특정 기기에서 빈 공간이 많이 남아 UI에서 어색함이 있었음 
이미지를 한 줄에 4개씩 보여지도록 grid 방식으로 변경하여 기기의 크기에 상관없이 일관된 UI를 유지할 수 있게 변경하였음 

[FIX] 7차 스프린트 QA 반영 사항 추가
